### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Francofrizza** [Saphjyr/ElytraChestplateSwapper2#2]
When I press the key, the Elytra doesn't turn on, 1.21.4, fabric, lunar client

**Comment by Saphjyr** [comment]
Thanks for reporting the issue.

I ran the mod with lunar client out of the box v3.5.2 on a 1.21.4 instance and I could not reproduce the bug.

Did you use other mods ? Can you put here the game logs after the bug happed please ?

**Comment by Francofrizza** [comment]
I only use that one and sodium, there are no logs, I only press the key in the game and it doesn't work

**Comment by Saphjyr** [comment]
You also need the FabricAPI, which is required by this mod. Lunar should have installed it by default but if it didn't make sure it's installed.

<img width="1440" height="896" alt="Image" src="https://github.com/user-attachments/assets/3347ecb7-e18d-40c5-a365-94ed215f787e" />

For the logs, there should be a lunar console window (named "mission control") that opens when a minecraft instance starts.

**Comment by Francofrizza** [comment]
I have it, the problem is that in the game I hit the key and it doesn't change my elytras

**Comment by Saphjyr** [comment]
Ok so I think I found the isssue. This is indeed a bug of ECS that has been fixed for version 1.21.9 and higher (ECS 2.0.1).

When the language of the game is not english, the mod cannot find chestplates in the inventory and does nothing.

Here is a fixed version for 1.21.2 to 1.21.4
https://www.curseforge.com/minecraft/mc-mods/elytra-chestplate-swapper/files/7179580

I hope this helps 😀

**Comment by Francofrizza** [comment]
It still doesn't work, ahhhh, I don't know what to do anymore

**Comment by Saphjyr** [comment]
Sorry, I can't find your issue.

Here are a few things that you can try, but it's probably not relevent:
 - Update to the latest version of minecraft (1.21.10).
- Check that the swap key is correct in your settings, and try to rebind it to another key.
- Try other similar mods and see if the issue persits.
